name: Frontend Automated Tests and Linting

on:
  push:
    branches: ['main']

jobs:
  test-prettier-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.12.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install packages
        run: |
          cd frontend
          yarn

      - name: Run Tests
        run: |
          cd frontend
          yarn test

      - name: Run Lint
        run: |
          cd frontend
          yarn lint

      - name: Run Build
        run: |
          cd frontend
          yarn build

      - name: Coveralls
        uses: coverallsapp/github-action@master
        run: cd frontend
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
